# Generated by Django 5.2.4 on 2025-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySales',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('penjualan_per_kategori', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'penjualan_per_kategori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('total_nilai_transaksi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'kinerja_karyawan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopCustomers',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('pelanggan_teratas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pelanggan_teratas',
                'managed': False,
            },
        ),
    ]
