# Generated by Django 5.2.4 on 2025-07-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USAEmployeePhoneBook',
            fields=[
                ('full_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title_of_courtesy', models.CharField(max_length=50)),
                ('home_phone', models.IntegerField()),
            ],
            options={
                'db_table': 'soal_pertama',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EmployeePerformance',
        ),
    ]
