# Generated by Django 5.2.4 on 2025-07-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_usaemployeephonebook_delete_employeeperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepletedCategory',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_units_in_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'soal_ketiga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EuropeanProductAveragePrice',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('average_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'soal_kelima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavouriteShipper',
            fields=[
                ('company_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_orders', models.IntegerField()),
            ],
            options={
                'db_table': 'soal_keenam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FragileProducts',
            fields=[
                ('product_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('quantity_per_unit', models.TextField()),
                ('units_in_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'soal_keempat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerritoriesWithAllEmployees',
            fields=[
                ('territory_description', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'soal_kedua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopCustomer',
            fields=[
                ('company_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_spend', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'soal_kedelapan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopSupplier',
            fields=[
                ('company_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_supply', models.IntegerField()),
            ],
            options={
                'db_table': 'soal_ketujuh',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CategorySales',
        ),
        migrations.DeleteModel(
            name='TopCustomers',
        ),
    ]
