# Generated by Django 5.2.4 on 2025-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_depletedcategory_europeanproductaverageprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPhoneBook',
            fields=[
                ('full_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('entity_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'soal_kedelapan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalEmployeeInEveryRegion',
            fields=[
                ('region_description', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_employees', models.IntegerField()),
            ],
            options={
                'db_table': 'soal_ketujuh',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TopCustomer',
        ),
        migrations.DeleteModel(
            name='TopSupplier',
        ),
    ]
