# Generated by Django 5.2.4 on 2025-08-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_role_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_usa_employee', 'Can view USA Employee Phone Book'), ('view_territories_employees', 'Can view Territories With All Employees'), ('view_depleted_category', 'Can view Depleted Category'), ('view_fragile_products', 'Can view Fragile Products'), ('view_european_product_price', 'Can view European Product Average Price'), ('view_favourite_shipper', 'Can view Favourite Shipper'), ('view_total_employee_region', 'Can view Total Employee In Every Region'), ('view_general_phonebook', 'Can view General Phone Book')],
                'managed': False,
            },
        ),
    ]
