# Generated by Django 5.2.4 on 2025-08-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depletedcategory',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_depletedcategory', 'Can view Depleted Category')]},
        ),
        migrations.AlterModelOptions(
            name='europeanproductaverageprice',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_europeanproductaverageprice', 'Can view European Product Average Price')]},
        ),
        migrations.AlterModelOptions(
            name='favouriteshipper',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_favouriteshipper', 'Can view Favourite Shipper')]},
        ),
        migrations.AlterModelOptions(
            name='fragileproducts',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_fragileproducts', 'Can view Fragile Products')]},
        ),
        migrations.AlterModelOptions(
            name='generalphonebook',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_generalphonebook', 'Can view general phone book')]},
        ),
        migrations.AlterModelOptions(
            name='territorieswithallemployees',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_territorieswithemployees', 'Can view Territories With All Employees')]},
        ),
        migrations.AlterModelOptions(
            name='totalemployeeineveryregion',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_totalemployeeineveryregion', 'Can view Total Employee In Every Region')]},
        ),
        migrations.AlterModelOptions(
            name='usaemployeephonebook',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_usaemployeephonebook', 'Can view USA Employee Phone Book')]},
        ),
    ]
