# Generated by Django 5.2.4 on 2025-08-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_depletedcategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportPermissions',
        ),
    ]
